package leonardo.banking_transactions.entities;

public enum SecurityAuditEventType {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGIN_RATE_LIMITED,
    LOGIN_REJECTED,
    LOGIN_UNAVAILABLE,
    USER_REGISTRATION_SUCCEEDED,
    USER_REGISTRATION_REJECTED,
    USER_REGISTRATION_RATE_LIMITED,
    USER_REGISTRATION_UNAVAILABLE,
    PUBLIC_REQUEST_UNCLASSIFIED
}

