spring.datasource.url=jdbc:postgresql://localhost:5433/pix_simulation
spring.datasource.username=postgres
spring.datasource.password=0407
spring.datasource.driver-class-name=org.postgresql.Driver
 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
 
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=VGhpcy1pcy1hLXN1ZmZpY2llbnRseS1sb25nLXNlY3JldC1mb3ItaHNtYWMtc2lnbmluZw==
app.jwt.expiration=3600
